-- MySQL Script generated by MySQL Workbench
-- Fri Mar 28 10:32:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`planos_contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`planos_contas` (
  `codigo_conta` VARCHAR(28) NOT NULL,
  `descricao_conta` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo_conta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupo_demonstrativo_financeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grupo_demonstrativo_financeiro` (
  `codigo_grupo_dfp` INT NOT NULL,
  `grupo_dfp` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`codigo_grupo_dfp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresas` (
  `categoria_doc` VARCHAR(100) NULL DEFAULT NULL,
  `codigo_cvm` CHAR(6) NOT NULL,
  `cnpj_companhia` VARCHAR(45) NOT NULL,
  `descricao_atividade` VARCHAR(200) NULL DEFAULT NULL,
  `especie_controle_acionario` VARCHAR(100) NULL DEFAULT NULL,
  `identificador_documento` INT NULL DEFAULT NULL,
  `mes_encerramento_exercicio_social` SMALLINT NULL DEFAULT NULL,
  `nome_empresa` VARCHAR(100) NULL DEFAULT NULL,
  `nome_anterior_empresa` VARCHAR(100) NULL DEFAULT NULL,
  `pagina_web` VARCHAR(100) NULL DEFAULT NULL,
  `pais_custodia_valores_mobiliarios` VARCHAR(100) NULL DEFAULT NULL,
  `pais_origem` VARCHAR(100) NULL DEFAULT NULL,
  `setor_atividade` VARCHAR(100) NULL DEFAULT NULL,
  `situacao_emissor` VARCHAR(100) NULL DEFAULT NULL,
  `situacao_registro_cvm` VARCHAR(100) NULL DEFAULT NULL,
  `versao` SMALLINT NULL DEFAULT NULL,
  `data_registro_cvm` DATE NULL DEFAULT NULL,
  `data_nome_empresarial` DATE NULL DEFAULT NULL,
  `data_categoria_registro_cvm` DATE NULL DEFAULT NULL,
  `data_situacao_registro_cvm` DATE NULL DEFAULT NULL,
  `data_constituicao` DATE NULL DEFAULT NULL,
  `data_especie_controle_acionario` DATE NULL DEFAULT NULL,
  `data_referencia_documento` DATE NULL DEFAULT NULL,
  `data_situacao_emissor` DATE NULL DEFAULT NULL,
  `data_alteracao_exercicio_social` DATE NULL DEFAULT NULL,
  `dia_encerramento_exercicio_social` SMALLINT NULL DEFAULT NULL,
  `data_doc` DATE NULL DEFAULT NULL,
  `mes_doc` VARCHAR(4) NULL DEFAULT NULL,
  `ano_doc` VARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_cvm`, `cnpj_companhia`),
  UNIQUE INDEX `cnpj_companhia_UNIQUE` (`cnpj_companhia` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`parecer_demonstrativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`parecer_demonstrativo` (
  `cnpj_companhia` VARCHAR(20) NULL,
  `num_linha_parecer_declaracao` SMALLINT NULL,
  `tipo_parecer_declaracao` VARCHAR(101) NULL,
  `tipo_relatorio_auditor` VARCHAR(19) NULL,
  `texto_parecer_declaracao` VARCHAR(8000) NULL,
  `versao` SMALLINT NULL,
  `data_referencia_doc` DATE NULL,
  `data_doc` DATE NULL,
  `mes_doc` VARCHAR(4) NULL,
  `ano_doc` VARCHAR(4) NULL,
  INDEX `cnpj_companhia_idx` (`cnpj_companhia` ASC) VISIBLE,
  CONSTRAINT `cnpj_companhia`
    FOREIGN KEY (`cnpj_companhia`)
    REFERENCES `mydb`.`empresas` (`cnpj_companhia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`informacao_trimestral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`informacao_trimestral` (
  `codigo_conta` VARCHAR(28) NOT NULL,
  `cnpj_companhia` VARCHAR(45) NOT NULL,
  `codigo_cvm` CHAR(6) NULL DEFAULT NULL,
  `escala_monetaria` VARCHAR(100) NULL DEFAULT NULL,
  `grupo_dfp` INT NOT NULL,
  `moeda` INT NULL DEFAULT NULL,
  `ordem_exercicio` VARCHAR(9) NULL DEFAULT NULL,
  `conta_fixa` VARCHAR(1) NULL DEFAULT NULL,
  `versao` SMALLINT NULL DEFAULT NULL,
  `data_inicio_exercicio` DATE NULL DEFAULT NULL,
  `data_fim_exercicio` DATE NULL DEFAULT NULL,
  `data_referencia_doc` DATE NULL DEFAULT NULL,
  `valor_conta` DECIMAL(10,0) NULL DEFAULT NULL,
  `data_doc` DATE NULL DEFAULT NULL,
  `mes_doc` VARCHAR(4) NULL DEFAULT NULL,
  `ano_doc` VARCHAR(4) NULL DEFAULT NULL,
  INDEX `codigo_conta_idx` (`codigo_conta` ASC) VISIBLE,
  INDEX `cnpj_companhia_idx` (`cnpj_companhia` ASC) VISIBLE,
  INDEX `grupo_dfp` (`grupo_dfp` ASC) VISIBLE,
  CONSTRAINT `codigo_conta`
    FOREIGN KEY (`codigo_conta`)
    REFERENCES `mydb`.`planos_contas` (`codigo_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `grupo_dfp`
    FOREIGN KEY (`grupo_dfp`)
    REFERENCES `mydb`.`grupo_demonstrativo_financeiro` (`codigo_grupo_dfp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cnpj_companhia`
    FOREIGN KEY (`cnpj_companhia`)
    REFERENCES `mydb`.`empresas` (`cnpj_companhia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`parecer_trimestral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`parecer_trimestral` (
  `cnpj_companhia` VARCHAR(20) NOT NULL,
  `num_linha_parecer_declaracao` SMALLINT NULL DEFAULT NULL,
  `tipo_parecer_declaracao` VARCHAR(101) NULL DEFAULT NULL,
  `tipo_relatorio_especial` VARCHAR(19) NULL DEFAULT NULL,
  `texto_parecer_declaracao` VARCHAR(8000) NULL DEFAULT NULL,
  `versao` SMALLINT NULL DEFAULT NULL,
  `data_referencia_doc` DATE NULL DEFAULT NULL,
  `data_doc` DATE NULL DEFAULT NULL,
  `mes_doc` VARCHAR(4) NULL DEFAULT NULL,
  `ano_doc` VARCHAR(4) NULL DEFAULT NULL,
  INDEX `cnpj_companhia_idx` (`cnpj_companhia` ASC) VISIBLE,
  CONSTRAINT `cnpj_companhia`
    FOREIGN KEY (`cnpj_companhia`)
    REFERENCES `mydb`.`empresas` (`cnpj_companhia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`formulario_referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`formulario_referencia` (
  `cnpj_companhia` VARCHAR(20) NOT NULL,
  `categoria_doc` VARCHAR(20) NULL DEFAULT NULL,
  `denominacao_companhia` VARCHAR(100) NULL DEFAULT NULL,
  `id_doc` INT NULL DEFAULT NULL,
  `link_doc` VARCHAR(121) NULL DEFAULT NULL,
  `versao` DECIMAL NULL DEFAULT NULL,
  `data_recebimento_doc` DATE NULL DEFAULT NULL,
  `data_referencia_doc` DATE NULL DEFAULT NULL,
  `data_doc` DATE NULL DEFAULT NULL,
  `mes_doc` VARCHAR(4) NULL DEFAULT NULL,
  `ano_doc` VARCHAR(4) NULL DEFAULT NULL,
  INDEX `cnpj_companhia_idx` (`cnpj_companhia` ASC) VISIBLE,
  CONSTRAINT `cnpj_companhia`
    FOREIGN KEY (`cnpj_companhia`)
    REFERENCES `mydb`.`empresas` (`cnpj_companhia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`periodicos_eventuais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`periodicos_eventuais` (
  `cnpj_companhia` VARCHAR(20) NOT NULL,
  `codigo_cvm` VARCHAR(6) NULL DEFAULT NULL,
  `assunto` TEXT NULL DEFAULT NULL,
  `categoria_doc` VARCHAR(100) NULL DEFAULT NULL,
  `especie` VARCHAR(100) NULL DEFAULT NULL,
  `link_doc` VARCHAR(168) NULL DEFAULT NULL,
  `nome_companhia` VARCHAR(100) NULL DEFAULT NULL,
  `protocolo_entrega` CHAR(30) NULL DEFAULT NULL,
  `tipo` VARCHAR(100) NULL DEFAULT NULL,
  `tipo_apresentacao` VARCHAR(33) NULL DEFAULT NULL,
  `versao` SMALLINT NULL DEFAULT NULL,
  `data_entrega_doc` DATE NULL DEFAULT NULL,
  `data_referencia_doc` DATE NULL DEFAULT NULL,
  `data_doc` DATE NULL DEFAULT NULL,
  `mes_doc` VARCHAR(4) NULL DEFAULT NULL,
  `ano_doc` VARCHAR(4) NULL DEFAULT NULL,
  INDEX `cnpj_companhia_idx` (`cnpj_companhia` ASC) VISIBLE,
  CONSTRAINT `cnpj_companhia`
    FOREIGN KEY (`cnpj_companhia`)
    REFERENCES `mydb`.`empresas` (`cnpj_companhia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`demonstrativo_financeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`demonstrativo_financeiro` (
  `codigo_conta` VARCHAR(28) NOT NULL,
  `cnpj_companhia` VARCHAR(45) NOT NULL,
  `codigo_cvm` CHAR(6) NULL DEFAULT NULL,
  `escala_monetaria` VARCHAR(100) NULL DEFAULT NULL,
  `grupo_dfp` INT NOT NULL,
  `moeda` INT NULL DEFAULT NULL,
  `ordem_exercicio` VARCHAR(9) NULL DEFAULT NULL,
  `conta_fixa` VARCHAR(1) NULL DEFAULT NULL,
  `versao` SMALLINT NULL DEFAULT NULL,
  `data_inicio_exercicio` DATE NULL DEFAULT NULL,
  `data_fim_exercicio` DATE NULL DEFAULT NULL,
  `data_referencia_doc` DATE NULL DEFAULT NULL,
  `valor_conta` DECIMAL(10,0) NULL DEFAULT NULL,
  `data_doc` DATE NULL DEFAULT NULL,
  `mes_doc` VARCHAR(4) NULL DEFAULT NULL,
  `ano_doc` VARCHAR(4) NULL DEFAULT NULL,
  INDEX `codigo_conta_idx` (`codigo_conta` ASC) VISIBLE,
  INDEX `cnpj_companhia_idx` (`cnpj_companhia` ASC) VISIBLE,
  INDEX `grupo_dfp` (`grupo_dfp` ASC) VISIBLE,
  CONSTRAINT `codigo_conta0`
    FOREIGN KEY (`codigo_conta`)
    REFERENCES `mydb`.`planos_contas` (`codigo_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `grupo_dfp0`
    FOREIGN KEY (`grupo_dfp`)
    REFERENCES `mydb`.`grupo_demonstrativo_financeiro` (`codigo_grupo_dfp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cnpj_companhia0`
    FOREIGN KEY (`cnpj_companhia`)
    REFERENCES `mydb`.`empresas` (`cnpj_companhia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`numeros_acoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`numeros_acoes` (
  `cnpj_companhia` VARCHAR(45) NOT NULL,
  `denominacao_companhia` VARCHAR(255) NULL,
  `qtd_acoes_ordinarias_capital_integralizado` BIGINT NULL,
  `qtd_acoes_preferenciais_capital_integralizado` BIGINT NULL,
  `qtd_total_acoes_capital_integralizado` BIGINT NULL,
  `qtd_acoes_ordinarias_tesouro` BIGINT NULL,
  `qtd_acoes_preferenciais_tesouro` BIGINT NULL,
  `qtd_total_acoes_tesouro` BIGINT NULL,
  `versao` INT NULL,
  `data_referencia_doc` DATE NULL,
  `data_doc` DATE NULL,
  `mes_doc` VARCHAR(4) NULL,
  `ano_doc` VARCHAR(4) NULL,
  UNIQUE INDEX `cnpj_companhia_UNIQUE` (`cnpj_companhia` ASC),
  CONSTRAINT `cnpj_companhia`
    FOREIGN KEY (`cnpj_companhia`)
    REFERENCES `mydb`.`empresas` (`cnpj_companhia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
